### ISSUE TITLE
git submodule too confusing?

### ISSUE THREAD

**Issue by katjav** [pure-data/helloworld#4]
To be honest I'm not happy with the git submodule for pd-lib-builder in this project. Do we really want to confront a beginning pd developer with one of the most confusing git topics? I can see how it is useful for certain projects, but here it is mainly an extra obstacle in an introduction to pd lib building. The submodule doesn't (automatically) point to the newest pd-lib-builder version anyway so it's hard to explain in a few words why you would use it.

**Comment by chr15m** [comment]
It's a good point.

**Comment by umlaeute** [comment]
maybe we could switch to [`git subtree`](https://lists.puredata.info/pipermail/pd-list/2014-11/108380.html) instead, which - afaiu - can be completely ignored...

i have to admit that i've never used `git subtree` before...

**Comment by danomatika** [comment]
I'd say drop the submodule and include info in the readme about using one, if the developer desires. Or at least maybe a link to info about submodules. I agree it's a bit obtuse if you're just starting with git.

In either case, we need to keep the pd-lib-builder copy/submodule commit up to date!

**Comment by danomatika** [comment]
At this point, as long as the readme is explicit about cloning with --recursive then things should be fine. When I've taught git to beginners, they haven't had much trouble as long as there are clear instructions (and they read said instructions). This is the strategy we're using with libpd.

I can update the readme regarding this.
